<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Favicon content -->
<link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/images/safari-pinned-tab.svg" color="#0078d7">
<meta name="msapplication-TileColor" content="#0078d7">
<meta name="theme-color" content="#0078d7">

<!-- Bootstrap 4.3.1 -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<!-- Main stylesheet -->
<link rel="stylesheet" href="/css/style.css">

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-134698258-1"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'UA-134698258-1');
</script>	<title>Terms of Service | Insight</title>
	<meta name="description" content="">
    <link rel="canonical" href="https://www.insightapp.co/privacy">
</head>
<body>
	<!--
<nav class="navbar container">
    <a class="navbar-brand" href="/">
    	<img src="/images/insight-logo.svg" width="146" height="40" alt="Insight - Share Your Knowledge" title="Insight Logo">
    </a>   
</nav>
-->
<nav class="container navbar navbar-expand-lg">
    <a class="navbar-brand" href="/">
    	<img src="/images/insight-logo.svg" width="146" height="40" alt="Insight - Share Your Knowledge" title="Insight Logo">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#frontend-nav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="frontend-nav">
	    <ul class="navbar-nav ml-auto">
			<li class="nav-item">
				<a class="nav-link" href="/login">Log In</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="/create-account">Create an Account</a>
			</li>
	    </ul>
    </div>
</nav>	
	<section class="container padding-60-15 max-width-860">
		<h1>Terms of Service</h1>
		<p><br><strong>A. The Terms</strong></p>
        <p><strong>1. Acceptance of Terms</strong> <br />By clicking "I Agree" on the account registration or payment page or using the Site in any way, you are agreeing to comply with and be bound by this Agreement, the <a href="/privacy"  rel="noopener">Privacy Policy,</a> and all rules, policies, and disclaimers posted on the Site or about which you are notified (collectively "Terms"). Please review all of the Terms carefully before using the Site.</p>
        <p><strong><em> By using the Site, you (i) agree to be bound by the Terms, (ii) represent that you are over the age of thirteen (13) and able to form legally binding contracts, (iii) agree and acknowledge that by using the Service you are accepting a benefit that cannot be disgorged, (iv) acknowledge that the service is subject to U.S. export controls and agree that you will comply with U.S. export controls, and (v) represent that you are neither located in a sanctioned country nor a prohibited person. </em></strong></p>
        <p><strong>PLEASE NOTE THAT THESE TERMS PROVIDE THAT IF YOU AND INSIGHT ARE UNABLE TO RESOLVE ANY DISPUTES THAT ARISE EITHER INFORMALLY OR THROUGH MEDIATION, THE DISPUTE WILL BE RESOLVED BY BINDING ARBITRATION. ARBITRATION USES A NEUTRAL ARBITRATOR INSTEAD OF A JUDGE OR JURY. YOU AND INSIGHT ALSO AGREE THAT ANY CLAIMS OR DISPUTES CANNOT BE BROUGHT AS A CLASS ACTION. PLEASE CAREFULLY REVIEW THE DISPUTE RESOLUTION SECTION. IF YOU DO NOT ACCEPT THE ARBITRATION PROVISION BELOW, YOU MAY NOT USE THE SITE.</strong></p>
        <p><strong><em> THESE TERMS ALSO EXPLAIN THE CONSENT YOU PROVIDE TO US TO CONTACT YOU USING THE TELEPHONE NUMBERS YOU PROVIDE TO US, INCLUDING VIA AUTOMATED DIALING OR TEXTING SYSTEMS.</em></strong></p>
        <p><strong>2. Definitions</strong> <br />The words "User," "you" and "your" refer to the individual or entity that creates an Insight account as a Customer and/or Expert. "Insight," "we," "us" and "our" refer to Insight. "Customer" refers to the person who asks a question on the Site. "Expert" refers to the person who answers a question on the Site.</p>
        <p><strong>3. Communications and Right to Modify Terms</strong> <br />When you visit Insight or send us emails, you are communicating with us electronically as well as via e-mail, text message, calls and push notifications. You consent to receive communications from us through the means outlined above or by posting notices on the Site. You agree that all agreements, notices, disclosures and other communications that we provide to you electronically or through other means, satisfy any legal requirement that such communications be in writing. You agree to provide us with, and maintain in your Insight account profile, your current and active email address.</p>
        <p>Insight may modify any of the Terms at any time by posting them on the Site. Changes shall automatically be effective upon posting; provided, however, that those changes that Insight, in its sole discretion, deems material changes to the Terms will be effective as to an existing User upon the earlier of: (1) the agreement of the User; or (2) thirty (30) days after notice to the existing User from an @insightapp.co email address to the User's email address on file with Insight or via other means including, but not limited to, a pop-up or banner, message, or other conspicuous notice on the Insight website. If you affirmatively agree to the new terms, your agreement will be effective immediately. You agree to make any and all necessary arrangements so that you (and not your spam filter) receive all emails from Insight email addresses. Your continued use of the Service will signify your acceptance of the changes. If you do not accept the changes, your sole and exclusive remedy is to cancel your account and discontinue using the Site. <strong>The latest Terms will be posted on the Site, and you should always review them prior to using the Site.</strong></p>
        <p><strong>4. Telephone Consumer Protection Act Disclosure</strong> <br />Communications from Insight, including its agents, representatives, affiliates, or business partners, may include but are not limited to: operational communications concerning your account or use of the Insight Site, updates concerning new and existing features of the Site, marketing information and promotions run by us, our agents, representatives, affiliates, or business partners, and any news concerning Insight.</p>
        <p><strong>By entering your telephone number into the Insight website, you expressly agree to receive communications for the purposes identified above from us, our agents, representatives, affiliates, or business partners, via e-mail, SMS or text messages, phone calls, and push notifications. You further expressly agree that these communications, including phone calls, SMS or text messages, may be generated using automated technology, such as an automatic telephone dialing system, or artificial or prerecorded voice, and even if your telephone number(s) is listed on any corporate, state, or federal Do-Not-Call lists.</strong></p>
        <p>You represent that for the telephone number(s) that you have provided to us, you are the current subscriber or customary user and that you have the authority to provide the consent described above to be contacted at such number(s). You agree to promptly alert us whenever you stop using a particular telephone number. Standard charges may apply to the receipt of these calls or text messages.</p>
        <p>Information collected, including personal information may be shared with affiliates and third-party providers, who will use that information in accordance with their own privacy policies. Please visit our <a href="/privacy">Privacy Policy</a> for more information.</p>
        <p><strong>B. The Website</strong></p>
        <p><strong>5. Insight Is a Venue; Third-Party Content</strong> <br />The Insight Site is a venue for informational and educational purposes, owned and operated by Insight, that exists solely to broker relationships between Experts and potential Customers of those Experts who are interesting in purchasing their Expert services. Insight is not in the business of providing or selling information or education that is within any Expert's area of Expertise. Users of the Site, not Insight, provide the content in Posts (defined below). The Experts determine which questions to answer; Experts are not employees or agents of Insight but are independent service providers using the Site to sell their Expert knowledge to Customers and, as such, together with Customers, are simply Users of the Site.</p>
        <p>Insight is not involved in the conversations between Customers and Experts and does not refer Customers to or endorse or recommend particular Experts. You understand and acknowledge that Insight cannot and does not edit, modify, filter, screen, monitor, endorse or guarantee the content of Posts. Insight shall not be liable for any acts or omissions of Experts, content in Posts or the ability of Experts to answer questions. We cannot ensure that an Expert will complete a transaction. Notwithstanding the foregoing, Insight reserves the right, but is not obligated, to refuse to post or to remove any content and/or remove any User's access to the Site.</p>
        <p>EMERGENCY QUESTIONS AND CRISIS SITUATIONS (particularly regarding medical or mental health issues) should not be direct to the Site and should, instead be directed immediately by telephone or in-person to qualified professionals (e.g. in the U.S., call 911). The Site is not the appropriate venue to deal with such situations.</p>
        <p><strong>6. Posts Are Not Private or Confidential; Anonymity</strong> <br />The Site is an Internet-based forum. <strong>Information and materials submitted in the content of your questions, answers, requests for information, responses, profiles, signatures, qualifications, comments, and posts in the Expert Forum and other places where Users communicate on the Site (collectively "Posts") <em>is not private or confidential, nor is it protected by attorney-client, doctor-patient, or any other privilege, and it may be read, collected, and used by others.</em></strong> For example, search engines may index your questions, answers, and other Posts to allow them to appear in search engine results (e.g. if someone does a search on google.com or another search engine, your questions, answers, and other Posts on Insight.com that relate to the search may appear in the search results list). <strong>To help protect your privacy, use an anonymous user name and do not include information regarding your identity or contact information in your Posts.</strong></p>
        <p><strong>7. Verification; No Reliance on the Term "Expert"</strong> <br />Every Expert on the Site has had at least one credential relevant to the category in which they are answering questions verified by a third-party verification service, unless the Expert is answering questions in a category that is still being tested by Insight in "Beta." Details regarding the credential(s) verified for each verified Expert can be found by clicking the "What's This" link next to the "Verified" logo associated with each Expert. Other information about an Expert, not shown as verified, has been provided by the Expert but has not been verified. Use of the term "Expert" by Insight and on the Site is only meant to describe Users who answer questions on the Site, and not to guarantee any particular level of expertise of these Experts.</p>
        <p>Regarding the verification process, Insight contracts with third-party service providers to perform the verifications described above; Insight does not itself verify the credentials of the Experts. The results of the verifications are only as accurate as the information provided to and by the third-party verification services, as of the time of the providing of information to and by the third-party verification services. Insight makes effort to verify, including using a third-party identity verification service, but cannot warrant or guarantee an Expert's purported identity; user identification on the Internet is difficult. For these reasons, Insight cannot and does not represent, warrant or guarantee the truthfulness or accuracy of the credentials or identities of Users and information provided by Users including Experts. You acknowledge that Insight will not be liable for any loss or damages caused by your reliance on any information or content contained in Posts.</p>
        <p><strong>8. Information Not Advice; No Client-Professional Relationship</strong> <br /><strong>Answers of Experts on the Site are provided by Experts and are to be used by Customers for general information purposes only, not as a substitute for in-person evaluation or specific professional (medical, legal, veterinary, tax, financial, etc.) advice.</strong> For example, Experts in the Legal category will provide only general information about the law, and will not provide legal advice nor propose a specific course of action for a Customer. By answering questions, Experts do not intend to form, and do not form attorney-client or doctor-patient relationships with Users of the Site. The laws, regulations, other governing authorities, standards, practices and procedures that apply to your particular question may differ depending on your location and information typically discovered through in-person evaluations or visits. Experts in some categories may be licensed, certified, educated, employed by or have experience in only particular jurisdictions.</p>
        <p><strong>No professional-client relationships shall be formed on the Site.</strong> Communications on this Site are not confidential and shall not be the subject of any associated privileges. Communications on this Site are limited, as described above, do not involve in-person evaluations or visits, and do not include safeguards and procedures typical of in-person evaluations and visits.</p>
        <p>Before you can interact with an Expert, you will be required to agree to a Disclaimer reminding you of these and other important provisions of the Terms.</p>
        <p><strong>C. User Accounts</strong></p>
        <p><strong>9. User Accounts; Restricted Activities; Suspension or Termination of Service</strong> <br /><strong>User Accounts.</strong> When you register as a User on the Site, you can establish a user name and password for access to your online account. You are responsible for maintaining the confidentiality of your user name, password, and account data, and you may not share this information or your account with anyone else, and you will be solely responsible for all acts or omissions that occur under your account. You will immediately notify Insight of any unauthorized use of your password or account. You should only create one account on the Site. If your Insight account has been suspended or terminated, you may not open another account on the Site.</p>
        <p>You agree to keep your contact and billing information (including but not limited to email address) up-to-date, and to comply with all billing procedures, including providing and maintaining accurate and lawful billing information for active Insight accounts.</p>
        <p><strong>Bound by Representatives.</strong> You are responsible for and bound by the actions of, and transactions entered into by, your actual and appointed representatives whether authorized by you in writing, verbally, or otherwise to represent you at or with Insight. You are responsible for monitoring your appointed representatives and protecting the privacy of your username, login information and any other account or financial information provided to Insight or its vendors and agree to inform us immediately, in writing, of any unauthorized use of same. If you are checking in or logging in as a representative for anyone other than yourself, you agree that you are a duly appointed and authorized representative for that person or entity and have authority to bind that person or entity to any actions or transactions you conduct.</p>
        <p><strong>Restricted Activities.</strong> You agree that any content you provide on the Site and your use of our Site or any Additional Services (whether such Additional Services are Informational or Beyond-Information Only, as defined below) initiated through the Site shall not: (a) be fraudulent, inaccurate or misleading; (b) infringe any third party's proprietary rights or rights of publicity or privacy; (c) be illegal or violate any federal, state or local law, statute, ordinance, regulation or ethical code; (d) be defamatory, trade libelous, unlawfully threatening or unlawfully harassing; (e) be obscene or contain child pornography or, if otherwise adult in nature or harmful to minors, but without containing child pornography; (f) contain any viruses, Trojan horses, or other computer programming routines that may damage, detrimentally interfere with, surreptitiously intercept or expropriate any system, data or personal information; (g) create liability for us or cause us to lose (in whole or in part) the services of our ISPs or other suppliers; or (h) link directly or indirectly to or include descriptions of goods or services that are prohibited under the Terms or that you do not have a right to link to or include. You may not consummate any transaction that was initiated using our Service that, by paying to us a fee, could cause us to violate any applicable law, statute, ordinance or regulation. Furthermore, you may not resell or make any commercial use of our system or the content on the Site without Insight's prior written consent. We do not knowingly collect personal information from children under 13 years of age, and if we become aware that a child under the age of 13 has submitted personal information to us, we will promptly remove it from our systems.</p>
        <p><strong>Suspension or Termination of Service.</strong> Customers may terminate your service and account at your sole discretion and at any time by written notice via e-mail to <a href="mailto:hello@insightapp.co">hello@insightapp.co.</a> Terminations typically will be effective within seven business days after our receipt of your termination notice, at which time your account will be closed and you will no longer enjoy access to your former account. Any fees accrued as of the effective date of termination will be payable according to the Terms. The procedure for Experts to terminate their accounts is set forth in the Expert Agreement.</p>
        <p>At any time, with or without notice, for any or no reason, Insight reserves the right to modify or discontinue any portion or all of the Site or Services, and to restrict, suspend and terminate Customers' accounts. The procedure for termination by Insight of Experts' accounts is set forth in the Expert Agreement.</p>
        <p><strong>Terms and Conditions Specific to Mobile Applications.</strong> Once you have registered as a User on the Site, you may elect to download and use different versions of the Insight mobile application (the "App"). Download and use of the App is completely optional. By downloading and using one or more versions of the Insight App, you agree that in addition to this Agreement governing your use of the App and the Insight , the following terms and conditions specifically applicable to your use of the App (the "Mobile Terms") also apply to you:</p>
        <p>(a) You acknowledge that the Mobile Terms and the Agreement is between you and Insight, and not any other third-party beneficiary (as defined below in (b)) and you understand that Insight is solely responsible for the App;</p>
        <p>(b) Additionally, Apple, Google, Inc., Microsoft Corporation or BlackBerry Limited will be a third-party beneficiary to this contract if you access the Insight platform using Applications developed for Apple iOS, Android, Microsoft Windows, or Blackberry-powered mobile devices, respectively;</p>
        <p>(c) Your access and use of the Insight App using these devices is subject to terms set forth in the applicable third-party beneficiary's terms of service;</p>
        <p>(d) The third-party beneficiaries listed above are not parties to this Agreement and are not responsible for the provision or support of the Insight platform in any way;</p>
        <p>(e) If you are accessing the Insight App through an Apple device, you acknowledge that Apple and its subsidiaries (collectively, "Apple") are third party beneficiaries of the Agreement and upon your download of and use of the App indicating your assent and agreement to the Mobile Terms, Apple will have the right (and will be deemed to have accepted the right) to enforce the Mobile Terms against you as a third party beneficiary thereof.</p>
        <p><strong>10. Charges, Rating the Expert, Refund and Cancellation Policy</strong> <br />Insight's platform allows Customers to post questions to Experts in subject-matter categories, facilitates communication with Experts via chat, emails, and online message boards, and enables delivery of answers to your questions, among other services ("Site Access Benefits"). Customers on the Site or may be presented with one of three payment models: (1) pay-per-question model; (2) membership model; and (3) additional services model (which is explained in Section E below).</p>
        <p><strong>Pay-Per-Question.</strong> With the pay-per-question model, you select the price that you are willing to pay for the Site Access Benefits related to a single question. Once you have selected the price and submitted your payment information, your question may be posted on Insight. Customers are charged in one of three ways depending on the payment source, as described on the payment page: (i) when the question is posted; (ii) at the time an Expert responds to the Customer's question; or (iii) $5 upon the posting of a question, with the remainder charged at the time an Expert responds.</p>
        <p><strong>Membership.</strong> Memberships allow Customers to receive Site Access Benefits for multiple questions on the Site for a monthly or other-period recurring fee. Customers who elect to pay for memberships are hereinafter referred to as "Members." The fee is automatically charged to the Member's payment source provided on the Site and placed in the Customer Payment Pool (account of all Members' payments). Insight will send at least one email notice of upcoming auto-renewal prior to auto-renewing your membership. Auto-renewal will remain in effect until withdrawn by you or terminated by Insight. You can stop auto-renewal of your membership by (1) clicking the cancel membership button on either the help center page or your account's membership page; (2) sending a written notice of cancellation via e-mail to <a href="mailto:hello@insightapp.co">hello@insightapp.co</a>. Your withdrawal must be received by Insight at least 30 days before your renewal date to be effective with respect to the next billing cycle. At the end of each payment period, any portion of the Insight Membership fee remaining in the Customer Payment Pool will be paid to Insight as compensation for the Site Access Benefits to which you were entitled during the payment period.</p>
        <p><strong>Rating the Expert.</strong> Experts typically respond to Customers' questions quickly. If the Expert requests further information before answering your question, you may wish to take advantage of the opportunity to provide more information to the Expert to allow the Expert to help you better.</p>
        <p>Once the Expert answers your question, you will be asked to rate the Expert. If you provide a rating of 1 or 2, you will be asked to provide the Expert with feedback about why you are unsatisfied, so the Expert may try to help you better. By posting a question and clicking to retrieve your answer, you are authorizing Insight to charge your payment source (for example, the credit card or PayPal account you provided to Insight). A portion of your payments may be paid to the Expert instead of to Insight.</p>
        <p>Insight does not guarantee that you will receive a response from an Expert, or that you will be satisfied with your communication with an Expert. For Pay-Per-Question Customers, in the rare instance that no Expert responds at all to your question, you agree that any amount up to $5 that was charged upon posting of your question may be retained by Insight in consideration for the Site Access Benefits received. See Refunds section below for information on requesting a refund.</p>
        <p><strong>Memberships - Additional Terms.</strong> Insight Memberships are intended and authorized only for personal, non-transferrable, not-for-resale use only. Insight should not be used for purposes of plagiarism in any context or in cheating in the academic setting. Notwithstanding any other terms, Insight reserves the right to cancel your Insight Membership in its entirety at any time and for any reason, with or without prior notice, including, but not limited to, your excessive use (as determined by Insight in its sole discretion). In the event that Insight cancels a Insight Membership, it will refund the current period's fee.</p>
        <p>In order to prevent fraudulent use of the Membership program by Customers, Customers who have purchased Memberships are ineligible to participate as Experts on Insight during the term of their Membership, as are their immediate family members (spouse, parent, child, sibling and spouse or "step" of each) and those living in the same households (persons, whether related or not, who lived in the same residence as the Member for at least three (3) months during the twelve (12)-month period preceding the start of the Insight Membership).</p>
        <p><strong>Refunds, Cancellations, Abuse and Special Programs.</strong></p>
        <p>No Refunds except as set forth herein. All membership fees are non-refundable except for the $5.00 trial membership fee. Memberships that are cancelled in the middle of the payment period will not have pro-rated billing, refunds or other credits. To cancel a Membership, you may contact Customer Service 24 hours a day, 7 days a week at 888-587-8220, or log into your Insight account.</p>
        <p>Insight maintains the right to initiate special incentive pricing, membership, and other programs. These may be limited, at Insight's sole discretion, to defined and limited Users or non-Users. Any promotional monies or credits placed into Customer accounts by Insight for use towards Site Access Benefits on the Site remain the property of Insight (they never become the property of Customers and never become refundable to the Customer), and unless otherwise stated on the Site or in an email to a Customer, will be usable only for thirty (30) days.</p>
        <p><strong>11. Receipt of Special Offers and Other Communications</strong> <br />By accepting these Terms, you agree to receive coupons, special offers, and other communications from Insight per the terms of the <a href="/privacy">Privacy Policy</a>. You may modify this setting by making the relevant changes to your Insight profile.</p>
        <p><strong>D. Legal Statements</strong></p>
        <p><strong>12. Release</strong> <br />Users are responsible for their acts and omissions and content placed on the Site. Insight will not be liable to Users for any disputes that may arise between or among Users.</p>
        <p><strong>13. Confidentiality</strong> <br />You acknowledge that Insight and its licensors and suppliers own the rights to the Insight website and the content displayed on the Site other than Posts. You shall not modify, reverse engineer, decompile, disassemble, or attempt to derive the source code of the Insight website, any software distributed by or assist any other person or entity in doing so. You acknowledge that all content, including, but not limited to, text, software, music, sound, photographs, video, graphics or other material contained in listings, sponsor advertisements or email-distributed, commercially produced information presented to you by the Service, by Insight, Insight Users, or Insight Advertisers or other content providers, is protected by copyrights, trademarks, service marks, patents or other proprietary rights and laws. You may not modify, copy, reproduce, republish, upload, post, transmit, or distribute in any way content available through the Service, whether done directly or through intermediaries (including, but not limited to, by means of spiders, robots, crawlers, scrapers, framing, iframes or RSS feeds) including code and software for commercial purposes. For permission to use third-party materials appearing on the Site, please contact the copyright owner. You do not acquire ownership rights to any content, document or other materials viewed through the Site. The posting of information or materials on the Site does not constitute a waiver of any right in such information and materials.</p>
        <p>Any access to or use of Insight to design, develop, test, update, operate, modify, maintain, support, market, advertise, distribute or otherwise make available any program, application or service (including, without limitation, any device, technology, product, computer program, mobile device application, website, or mechanical or personal service) that enables or provides access to, use of, operation of or interoperation with Insight (including, without limitation, to access content, post content, cross-post content, re-post content, respond or reply to content, verify content, transmit content, create accounts, verify accounts, use accounts, circumvent and/or automate technological security measures or restrictions, or flag content) without the prior written authorization of Insight is prohibited. This prohibition specifically applies, but is not limited to, software, programs, applications and services for use or operation on or by any computer and/or any electronic, wireless and/or mobile device, technology or product that exists now or in the future.</p>
        <p>If you access Insight or copy, display, distribute, perform or create derivative works from content displayed on the Site or other intellectual property in violation of the Terms of Service or for purposes inconsistent with the Terms of Service, your access, copying, display, distribution, performance or derivative work is unauthorized. Circumvention of any technological restriction or security measure on Insight or any provision of the Terms of Service that restricts content, conduct, accounts or access is expressly prohibited. For purposes of this paragraph, you agree that cached copies of Insight webpages on your computer or computer server constitute "copies" under the Copyright Act, 17 U.S.C. &sect; 101.</p>
        <p>You agree that Posts on the Site, materials, ideas, comments and testimonials you submit on the Site or other venues, including, but not limited to, the Insight blogs; the Insight venues on <a href="http://www.facebook.com">Facebook</a>, <a href="http://www.twitter.com">Twitter</a>, <a href="http://www.linkedin.com">LinkedIn</a>, <a href="http://www.youtube.com">YouTube</a>, <a href="http://www.pinterest.com">Pinterest</a>; the Site administrator; or any employee, officer or agent of Insight ("User Content"), will not be considered confidential and may be used by Insight, in its sole discretion, without any obligation to compensate for use of or to return any submitted materials. You also agree that Insight owns, and has the right to register in its name, trademarks and service marks for any category names that you create on Insight, so do not use a category name that you want to reserve for your own benefit. Insight may use other trademarks or service marks in lieu of the category names that you create.</p>
        <p>You grant to Insight a non-exclusive, irrevocable, perpetual, worldwide, royalty-free, sublicensable (through multiple tiers) right to exercise the copyright, publicity, and database rights, including the right to use, reproduce, display, edit, copy, modify, transmit, publicly perform, extract and create derivative works thereof, that you have in your Posts and User Content, in any media now known or not currently known, with respect to any such Posts and other User Content.</p>
        <p><strong>14. No Endorsement of Non-Insight Entity; No Relationship with Users</strong> <br />Insight may endeavor to offer to its Users products and services offered by non-Insight entities. The Site may contain links to third party websites and service providers (collectively, "Third Party Services") that are not owned or controlled by Insight. Insight has no control over and assumes no responsibility for the content, practices, and privacy policies of such Third Party Services. Insight encourages you to, and you acknowledge that you are solely responsible for, reviewing and complying with any third party terms and conditions and privacy policies. Insight cannot and will not censor or edit the content of any Third Party Service. Placement of information, logos, links or names of such non-Insight entities on the Site does not constitute an endorsement or warranty of these entities, their products or services. By using this Site, you agree that Insight is not responsible for, and you take full responsibility for, a decision to visit or patronize any such Third Party Service or entity, you hold Insight harmless from any and all liability arising from such actions, and you expressly relieve Insight from all liability arising from your use of Third Party Services. You further acknowledge that no relationship (such as partnership, agent, joint venturer, or employee) is created between you and Insight or between any User (including Customers and Experts) and Insight by formation of this Agreement (or any of the Terms) or by your participation on the Site. IT IS THE RESPONSIBILITY OF THE USER TO EVALUATE THE ACCURACY, COMPLETENESS AND USEFULNESS OF ANY OPINION, ANSWER OR OTHER CONTENT AVAILABLE THROUGH THE SITE, FROM THIRD PARTIES OR OBTAINED FROM A LINKED SITE. PLEASE SEEK THE ADVICE OF PROFESSIONALS, AS APPROPRIATE, REGARDING THE EVALUATION OF ANY SPECIFIC OPINION, ANSWER, PRODUCT, SERVICE, OR OTHER CONTENT.</p>
        <p><strong>15. Information Control and Storage</strong> <br />We do not control the information provided by Users, which you may find to be offensive, harmful, inaccurate, or deceptive. Please use caution and common sense when using the Site. There are also risks of dealing with underage persons or people acting under false pretenses. Additionally, there may be risks dealing with international trade and foreign nationals. By using this Site, you agree to accept such risks and that Insight is not responsible for the acts or omissions of Users on the Site.</p>
        <p>The amount of storage space per User is currently limited. You agree that Insight is not responsible or liable for the deletion or failure to store content and/or other information.</p>
        <p><strong>16. Exclusion of Warranties</strong> <br />Insight SERVICES, SOFTWARES, AND RELATED DOCUMENTATION ARE PROVIDED "AS IS" AND WITHOUT ANY WARRANTY OF ANY KIND EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. NO INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM US THROUGH THIS SITE SHALL CREATE ANY WARRANTY, REPRESENTATION OR GUARANTEE NOT EXPRESSLY STATED IN THESE TERMS. Insight DOES NOT REPRESENT OR WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THIS SITE OR THE SERVER THAT MAKES IT AVAILABLE, ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. Insight DOES NOT WARRANT OR REPRESENT THAT THE USE OR THE RESULTS OF THE USE OF THE MATERIALS AVAILABLE THROUGH THE SERVICE, FROM THIRD PARTIES OR A LINKED SITE WILL BE CORRECT, ACCURATE, TIMELY, RELIABLE OR OTHERWISE. SOME STATES OR OTHER JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU. YOU MAY ALSO HAVE OTHER RIGHTS THAT VARY FROM STATE TO STATE AND JURISDICTION TO JURISDICTION.</p>
        <p>UNDER NO CIRCUMSTANCES WILL Insight BE LIABLE FOR ANY LOSS OR DAMAGE CAUSED BY A USER'S RELIANCE ON INFORMATION OBTAINED THROUGH THE SITE, FROM THIRD PARTIES (SUCH AS EXPERTS OR OTHERS) OR A LINKED SITE, OR USER'S RELIANCE ON ANY PRODUCT OR SERVICE OBTAINED FROM A THIRD PARTY OR A LINKED SITE. USE OF THIS SITE IS AT USER'S SOLE RISK.</p>
        <p>NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM Insight OR THROUGH OR FROM THE SERVICES SHALL CREATE ANY WARRANTY.</p>
        <p><strong>17. Limitation of Liabilities</strong> <br />IN NO EVENT SHALL Insight, ITS PARENTS, SUBSIDIARIES, OFFICERS, DIRECTORS, SHAREHOLDERS, EMPLOYEES, AGENTS, JOINT VENTURERS, CONSULTANTS, SUCCESSORS OR ASSIGNS BE LIABLE FOR ANY INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, PUNITIVE OR EXEMPLARY DAMAGES (INCLUDING, BUT NOT LIMITED TO, LOSS OF BUSINESS, PROFITS, DATA, USE, REVENUE OR OTHER ECONOMIC ADVANTAGE), ARISING OUT OF, OR IN CONNECTION WITH, OUR SITE, OUR SERVICES OR THE TERMS BASED ON ANY THEORY, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE LIMITATION OF DAMAGES SET FORTH ABOVE IS A FUNDAMENTAL ELEMENT OF THE BASIS OF THE BARGAIN BETWEEN US AND YOU. THIS SITE AND THE INFORMATION WOULD NOT BE PROVIDED WITHOUT SUCH LIMITATIONS. IN NO EVENT WILL OUR LIABILITY, AND THE LIABILITY OF OUR PARENTS, SUBSIDIARIES, OFFICERS, DIRECTORS, EMPLOYEES, AND SUPPLIERS, TO YOU OR ANY THIRD PARTIES IN ANY CIRCUMSTANCE EXCEED THE GREATER OF (A) THE AMOUNT OF FEES YOU PAY TO Insight IN THE 12 MONTHS PRIOR TO THE ACTION GIVING RISE TO LIABILITY, OR (B) US$100. SOME STATES OR OTHER JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATIONS AND EXCLUSIONS MAY NOT APPLY TO YOU.</p>
        <p><strong>18. Indemnification</strong> <br />You agree to indemnify and hold Insight, its parents, subsidiaries, officers, directors, shareholders, employees, agents, joint venturers, consultants, successors and assigns harmless from and against all losses, costs, liabilities and expenses including reasonable attorneys' fees, asserted by any third-party that are in any way due to, or arising out of, your use of or conduct on the Site.</p>
        <p><strong>19. Press Releases and Third-Party Press about Insight</strong> <br />The Site may contain press releases and other information about Insight. While this information was believed to be accurate as of the date prepared, we disclaim any duty or obligation to update this information or any press releases. Information about companies other than ours contained in the press release or otherwise, should not be relied upon as being provided or endorsed by Insight. Likewise, third-party press about Insight or the Site should not be relied upon as being provided or endorsed by Insight.</p>
        <p><strong>20. Choice of Law </strong> <br />Except as set forth in Section D.21 below, the parties agree that this Agreement and any and all claims, causes of action or disputes (regardless of theory) between you and Insight arising out of or related to this Agreement, the Site and any services or content accessed therein will be governed by the laws of the State of Idaho, without regard to conflict or choice of law principles.</p>
        <p><strong>21. Dispute Resolution</strong> <br /><strong>If you are an Expert (as defined in the Expert Agreement) with a dispute, claim or controversy of any sort and of any nature (collectively, "dispute") against Insight in your capacity as an Expert, then the arbitration agreement in the Expert Agreement applies instead of this one. If your dispute with Insight is made in your capacity as User who is not an Expert, then the following dispute resolution provisions apply.</strong></p>
        <p><strong>This Section D.21 may be referred to as the parties' "Dispute Resolution Agreement." If you have a dispute with Insight or if Insight has a dispute with you and such dispute cannot be resolved informally, such dispute will be resolved on an individual basis in accordance with the provisions set forth below:</strong></p>
        <p>(a)Informal Resolution. Prior to initiating mediation or arbitration, the party with a grievance must:</p>
        <p>(i) Notify the other party, in writing, of the facts of the dispute and all damages claimed. Such a writing must be sent to the User's email address on file to&nbsp;<a href="mailto:hello@insightapp.co">hello@insightapp.co,</a> whichever is applicable ("Dispute Notification");</p>
        <p>(ii) The party receiving the Dispute Notification has thirty (30) days from receipt of the Dispute Notification to respond.</p>
        <p>(iii) The other party then has 15 days to reply to the response.</p>
        <p>(b)Mediation.. If the dispute is not resolved informally, either party may make a demand for mediation, with the other party's consent, by filing a: (i) Request for AAA Online Mediation for Claims under $10,000 with the American Arbitration Association ("AAA"); or (ii) Request for Mediation with the AAA. To file a request for mediation for a claim under $10,000, you must go to the following website: <a href="http://services.adr.org/eroom/faces/welcome_and_steps.jspx" target="_blank" rel="noopener">http://services.adr.org/eroom/faces/welcome_and_steps.jspx.</a> If that link does not work, please contact <a href="mailto:legal@Insight.com">legal@Insight.com</a> at Insight for updated information. If you are requesting mediation for a claim that is worth $10,000 or more, you must go to the following website to file such a claim: <a href="https://www.adr.org/aaa/faces/services/disputeresolutionservices/" target="_blank" rel="noopener">https://www.adr.org/aaa/faces/services/disputeresolutionservices/.</a> If that link does not work, please contact <a href="mailto:hello@insightapp.co">hello@insightapp.co</a> at Insight for updated information. If either party requests mediation and both parties consent to mediation, the costs of mediation will be borne equally by the parties.</p>
        <p><strong>(c) ARBITRATION. ANY DISPUTE NOT RESOLVED INFORMALLY OR THROUGH MEDIATION SHALL BE RESOLVED BY FINAL AND BINDING ARBITRATION SO LONG AS SUCH DISPUTES ARISE IN ANY WAY OUT OF THESE TERMS, ANY TRANSACTION WITH Insight, YOUR USE OF THE SITE AND/OR ANY Insight SERVICE, OR ANY AGREEMENT BETWEEN YOU AND Insight. THE ARBITRATION PROVISION EXTENDS TO DISPUTES UNDER THE TELEPHONE CONSUMER PROTECTION ACT ("TCPA"). </strong></p>
        <p><strong>YOU ACKNOWLEDGE THAT, BY AGREEING TO THESE TERMS, THAT THIS DISPUTE RESOLUTION AGREEMENT IS MADE IN THE COURSE OF INTERSTATE COMMERCE; AND THAT THE FEDERAL ARBITRATION ACT, 9 U.S.C. &sect;1 ET. SEQ. (THE "FAA") AND NOT STATE LAW GOVERNS THE INTERPRETATION AND ENFORCMENT OF THIS DISPUTE RESOLUTION AGREEMENT, INCLUDING THE ARBITRABILITY OF DISPUTES, WHICH SHALL BE DECIDED BY THE ARBITRATOR. THIS CHOICE OF LAW PROVISION APPLIES ONLY TO THIS DISPUTE RESOLUTION AGREEMENT, AND NOT TO THE REST OF THIS AGREEMENT OR TERMS.</strong></p>
        <p><strong>YOU FURTHER ACKNOWLEDGE THAT YOU AND Insight ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY REGARDING ANY DISPUTE. IT IS IMPORTANT THAT YOU UNDERSTAND THAT THE ARBITRATOR'S DECISION WILL BE BINDING AND MAY BE ENTERED AS A JUDGMENT IN ANY COURT OF COMPETENT JURISDICTION.</strong></p>
        <p><strong>Arbitration Procedures:</strong> Disputes shall be resolved by binding arbitration in accordance with the arbitration rules of the American Arbitration Association ("AAA") pursuant to its Consumer Arbitration Rules, as modified by the terms in this Dispute Resolution Agreement. Copies of these rules can be obtained at the AAA's website or by calling the AAA at 1-800-778-7879. Either party can initiate a demand for arbitration. Each party will be responsible for its own costs, including paying any AAA filing, administrative and arbitrator fees in accordance with AAA rules. The award rendered by the arbitrator may include costs of arbitration, reasonable attorneys' fees and reasonable costs for expert and other witnesses. In the event of any inconsistency between this Dispute Resolution Agreement and the applicable rules of the AAA, this Dispute Resolution Agreement shall govern.</p>
        <p><strong>Consent to Jurisdiction in California:</strong> The parties agree that the arbitration will be conducted in San Francisco, California unless you and Insight agree otherwise.</p>
        <p><strong>(d) <u>CLASS ACTION WAIVER. YOU AND Insight EXPRESSLY AGREE THAT: </u></strong></p>
        <p>(i)<strong><u> ANY ARBITRATION PROCEEDING WILL TAKE PLACE ON AN INDIVIDUAL BASIS; </u></strong></p>
        <p>(ii)<strong><u> YOU EXPRESSLY WAIVE YOUR ABILITY TO PARTICIPATE AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS, MASS, COLLECTIVE, PRIVATE ATTORNEY GENERAL OR OTHER REPRESENTATIVE PROCEEDING; </u></strong></p>
        <p>(iii)<strong><u> THERE SHALL BE NO CLASS CLAIMS, CONSOLIDATION, OR JOINDER ALLOWED IN ANY ARBITRATION BETWEEN THE PARTIES; (iv) IF THIS ARBITRATION AGREEMENT IS FOUND INAPPLICABLE TO YOUR DISPUTE WITH Insight, THIS CLASS ACTION WAIVER WILL CONTINUE TO APPLY IN LITIGATION; AND (v) YOU AGREE THAT THIS CLASS ACTION WAIVER IS AN ESSENTIAL ELEMENT OF OUR CONTRACT AND THESE TERMS AND THAT IT MAY NOT BE SEVERED. THE ARBITRATOR SHALL NOT CONSOLIDATE CLAIMS OF DIFFERENT USERS INTO ONE PROCEEDING, NOR SHALL THE ARBITRATOR HAVE THE POWER TO HEAR ARBITRATION AS A CLASS ACTION, COLLECTIVE ACTION, OR REPRESENTATIVE ACTION. SIMILARLY, ANY CLAIMS COVERED BY THIS DISPUTE RESOLUTION AGREEMENT THAT Insight MAY HAVE AGAINST USER MAY NOT BE BROUGHT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS ACTION, COLLECTIVE ACTION OR REPRESENTATIVE ACTION PROCEEDING. </u></strong></p>
        <p>(e) <u>Survivability; Right to Consult.</u> This Dispute Resolution Agreement shall survive expiration or termination of this Agreement for any reason. User acknowledges and agrees that he/she is entering into this Dispute Resolution Agreement voluntarily and without any duress or undue influence by Insight or anyone else. User further acknowledges and agrees that he/she has carefully read this Dispute Resolution Agreement and that User has asked any questions needed for User to understand the terms, consequences and binding effect of this Dispute Resolution Agreement and fully understand it, including that User is waiving his/her right to a jury trial. Finally, User agrees that he/she has been provided an opportunity to seek the advice of an attorney of User's choice before agreeing to this Dispute Resolution Agreement.</p>
        <p><strong>22. Agreement; Assignment; Miscellaneous</strong> <br />The Terms constitute the complete and exclusive statement of the Agreement between you and us on the subject matter addressed herein. It supersedes any and all prior or contemporaneous agreement, oral or written, and any other communications, representations, warranties and understanding relating to the subject matter of the Terms. For those Users who have become Experts, nothing in this Agreement supersedes the terms of the Expert Agreement, and in the event of a conflict between this Agreement (or later versions of this Agreement) and the Expert Agreement, the terms of the Expert Agreement shall prevail. If there is a conflict between an oral or written representation of any Insight employee or agent and the Terms (other than modifications to the Terms executed in writing by the CEO or authorized-in-fact representative of Insight), the Terms will prevail. To the extent the Terms are in conflict or inconsistent with one another, this Agreement and the Privacy Policy will prevail over other Terms of the Site; also, this Agreement, the Privacy Policy, and disclaimers will prevail over FAQs, and other rules and policies on the Site. If any provision(s) of the Terms is held by an arbitrator or court of competent jurisdiction to be contrary to law, then such provision(s) shall be construed, as nearly as possible, to reflect the intentions of the parties and the other provisions shall remain in full force and effect. Insight's failure to exercise or enforce any of the Terms shall not constitute a waiver of Insight's right to exercise or enforce the Terms as to the same or another instance. Headings in this Agreement are for purposes of reference only and shall not limit or otherwise affect the meaning of the Terms.</p>
        <p>You agree that Insight may assign the Terms to any other entity of its choosing, with or without notice to you. You may not assign the Terms to any other party for any reason, including, but not limited to, because your interaction with other users of the Site, the pricing offered, and fraud mechanisms in place, are based upon individual usage. Insight shall not be deemed to have waived any of its rights or remedies unless such waiver is in writing and signed by an officer of Insight. No delay or omission on the part of Insight in exercising any rights or remedies shall operate as a waiver of such rights or remedies or any other rights or remedies on future occasions. The section titles in the Terms are solely used for the convenience of the parties and have no legal or contractual significance.</p>
        <p>This Section, along with Sections 6, 10 (with respect to amounts remaining in your account as of termination), 11, 13, 16, 17, 18, 20, and 21 above will survive any termination of this Agreement.</p>
        <p><strong>E. Additional Services</strong></p>
        <p><strong>You may be presented with an offer for services outside of the Site's standard question-and-answer platform ("Additional Services").</strong></p>
        <p>Insight is only a venue which facilitates communication between Experts and potential Users of Additional Services. It does not provide any of the substance or content of any Additional Service initiated through Insight's platform.</p>
        <p><strong>Insight will in no way be liable for any acts or omissions of Experts in performing Additional Services (or any services) for you.</strong></p>
        <p><strong>23. Special Provisions Relating to Remote Desktop Users</strong></p>
        <p><strong>If you agree to accept Remote Desktop services (whether such services are Information Only or Beyond Information Only) from an Expert, you understand and agree that by accepting such offer for services, you are agreeing to give the Expert full access to and control over your computer (including permission to download and use software on your computer, gather system data, modify settings, etc.) for computer diagnosis, service and repair. You agree that any third-party software acquired, installed or used during the Remote Desktop session, by you or by the Expert, will be licensed to you, and that any terms of use relating to the third-party software are agreed to by you, that Insight may record via video the Remote Desktop Session for internal purposes, and that you will not use the Expert's services to do anything unlawful.</strong></p>
        <p><strong>24. Special Provisions Relating to Additional Services in the Legal, Medical, Health, Pet, and Large Animal Categories</strong></p>
        <p>Additional Services may be: (1) "Information Only;" or (2) "Beyond Information Only." "Information Only" Additional Services are those additional services outside the Site's standard question-and-answer platform and may be conducted off the Site (either by phone, chat, email, remote desktop or any other third-party tool) but remain for general informational services only. Additional Services that are "Beyond Information Only" facilitate Legal, Medical, Health, Pet, and Large Animal Category Users' exchange of services that are more than informational and that could potentially evolve into a professional relationship.</p>
        <p><strong>Information Only Premium Services:</strong></p>
        <p>If you decide to accept Information Only Additional Services, you understand that by receiving such Additional Services, you are agreeing to the following terms and conditions:</p>
        <p>a. Any Information Only Additional Services you receive from a legal, tax, medical or veterinary professional are for general informational purposes only.</p>
        <p>b. The legal, tax, medical or veterinary professional from whom you are receiving Information Only Additional Services is not acting as your attorney, tax advisor, doctor or veterinarian.</p>
        <p>c. The legal, tax, medical or veterinary professional from whom you are receiving Information Only Additional Services may not be licensed in the jurisdiction where you are located.</p>
        <p>d. The Information Only Additional Services are not subject to an attorney-client/ accountant-client/doctor-patient relationship or attorney-client/ accountant-client/doctor-patient privilege. Before applying the Information Only Additional Services to your specific situation, you should consult with a professional licensed to practice in your jurisdiction.</p>
        <p>e. Any amounts a Customer pays for Information Only Additional Services are divided into two distinct parts: (i) Insight's fee for enabling the request, offer and/or fulfillment of Additional Services and related services ("Additional Site Access Benefits"); and (ii) the Expert's fee for the specific Additional Service provided to the User. Insight does not share in any Expert's fee.</p>
        <p>f. Once you accept an offer for Information Only Additional Services, your payment method on file, if any, will be automatically charged the Additional Services amount. If you have already asked a question, received a response and have not yet rated the Expert, if you then proceed to accept such Expert's offer of Additional Services, you will be deemed to have accepted the response as if you had given such Expert a "5" rating (See Section 9, Rating the Expert, above).</p>
        <p><strong>Beyond Information Only Additional Services</strong></p>
        <p>If you decide to accept Beyond Information Only Additional Services, you understand that by receiving such Additional Services, you are agreeing to the following terms and conditions:</p>
        <p>a. Insight is not involved in any agreements between you and any Experts from whom you choose to receive Beyond Information Only Additional Services.</p>
        <p>b. Insight does not form any attorney-client/doctor-patient/accountant-client relationship with any User through its question-and-answer platform or by virtue of any Beyond Information Only Additional Services.</p>
        <p>c. Insight will endeavor to find an Expert relevant to your request for Additional Services Beyond Information Only. Nevertheless, Insight does not guarantee that any Expert who contacts you can fulfill your request for Additional Services Beyond Information Only. Providing a platform where potential Customers can engage the services of Experts who offer Additional Services Beyond Information Only does not imply an endorsement or recommendation for any particular Expert (except as specified in Section 7 above).</p>
        <p>d. Insight is not a law firm and it does not provide any legal advice, counsel, or recommendation to Users, nor is Insight a lawyer referral service.</p>
        <p>Payment for Beyond Information Only Additional Services will be described in the particular offer. Insight's payment structures take into consideration fee sharing restrictions under various professional ethics rules.</p>
	
	</section>
	
	<footer class="container-fluid dark-bg padding-40-15">
	<div class="container">
		<div class="row">
			<div class="col-md-3 col-sm-12">
				<a href="/"><img src="/images/insight-white-logo.svg" alt="Insight App" title="Insight" class="footer-logo"></a>
			</div>
			<div class="col-md-6 col-sm-12">
				<p class="text-white text-center footer-text">© <script>document.write(new Date().getFullYear());</script> Insight. Made with ♥️ in Nashville.<br>
					<a href="/privacy" class="footer-link">Privacy</a>&nbsp;&nbsp;&nbsp;&nbsp;
					<a href="/terms" class="footer-link">Terms</a>&nbsp;&nbsp;&nbsp;&nbsp;
					<a href="#" class="footer-link" data-toggle="modal" data-target="#media">Media</a>&nbsp;&nbsp;&nbsp;&nbsp;
					<a href="#" class="footer-link" data-toggle="modal" data-target="#contact">Contact</a>
				</p>
			</div>
			<div class="col-md-3 col-sm-12">
				<div class="center-sm">
					<a href="https://facebook.com/pg/Insight-370969843494917" target="_blank" class="footer-social"><i class="fab fa-facebook-square"></i></a>
					<a href="https://twitter.com/insightappco" target="_blank" class="footer-social"><i class="fab fa-twitter-square"></i></a>
					<a href="https://www.linkedin.com/company/insightappco" target="_blank" class="footer-social"><i class="fab fa-linkedin"></i></a>
					<a href="https://instagram.com/insightappco" target="_blank" class="footer-social"><i class="fab fa-instagram"></i></a>
				</div>
			</div>
		</div>
	</div>
</footer>

<!-- Contact Modal -->
<div class="modal fade" id="contact" tabindex="-1" role="dialog" aria-labelledby="contact-label" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="contact-label">Contact Us</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"><i class="fas fa-times"></i></span>
                </button>
            </div>
        <div class="modal-body">
            <p>If you have questions or need help with Insight, please email us at <a href="mailto:hello@insightapp.co">hello@insightapp.co</a>.</p>
        </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Dismiss</button>
            </div>
        </div>
    </div>
</div>

<!-- Media Modal -->
<div class="modal fade" id="media" tabindex="-1" role="dialog" aria-labelledby="media-label" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="media-label">Media Inquiries</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"><i class="fas fa-times"></i></span>
                </button>
            </div>
        <div class="modal-body">
            <p>Coming Soon.</p>
        </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Dismiss</button>
            </div>
        </div>
    </div>
</div>
        
<!-- Cookie Policy -->
<div id="cookieAcceptBar" class="cookieAcceptBar animated fadeInUp" style="display: none;">
    <div class="font-22">🍪</div> &nbsp;By browsing this website, you consent to our <a href="/privacy">privacy policy</a> — <button id="cookieAcceptBarConfirm">I agree</button>
</div>

<!-- FontAwesome 4 -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

<!-- Animate.css -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js"></script>

<script>
    $(document).ready(function() {        
        if(window.location.href.indexOf('#media') != -1) {
            $('#media').modal('show');
        }
        
        if(window.location.href.indexOf('#contact') != -1) {
            $('#contact').modal('show');
        }
        cookiesPolicyBar();
    });
    
    function cookiesPolicyBar() {
	    if ($.cookie('cookieAccept') == null) { $('#cookieAcceptBar').show();} else {$('#cookieAcceptBar').hide(); }
	    $('#cookieAcceptBarConfirm').on('click',function(){
	        $.cookie('cookieAccept', 'active', { expires: 90 });
	        $('#cookieAcceptBar').hide();
	    });
	}
</script></body>
</html>








